# Generated by Django 3.0.8 on 2020-08-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
