# Generated by Django 3.0.8 on 2020-08-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='store/images/avatar-placeholder.png', null=True, upload_to=''),
        ),
    ]
