# Generated by Django 3.0.8 on 2020-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200817_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar-placeholder.png', null=True, upload_to=''),
        ),
    ]
