# Generated by Django 3.0.8 on 2020-08-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20200817_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='in_fav',
        ),
    ]
